const tags = [
    "Web Development",
    "App Development",
    "Hacking",
    "Data Science",
    "Machine Learning",
    "Artificial Intelligence",
    "Blockchain",
    "Cloud Computing",
    "Internet of Things (IoT)",
    "Cybersecurity",
    "Game Development",
    "DevOps",
    "AR/VR Development",
    "UX/UI Design",
    "Backend Development",
    "Frontend Development",
    "Software Testing",
    "Data Analysis",
    "Big Data",
    "Mobile Development",
    "Full Stack Development",
    "Digital Marketing",
    "Embedded Systems",
    "Robotics",
    "Networking",
    "Database Management",
    "API Development",
    "Software Engineering",
    "Continuous Integration",
    "System Design",
    "Quantum Computing",
    "Open Source",
    "Scripting",
    "Server Management",
    "Desktop Development",
    "E-commerce Development",
    "Progressive Web Apps (PWA)",
    "Code Optimization",
    "Testing & Debugging",
    "Cloud Architecture",
    "Containerization (Docker, Kubernetes)",
    "Artificial Neural Networks",
    "Firmware Development",
    "Natural Language Processing (NLP)",
    "Automation",
    "Penetration Testing",
    "Web3",
    "SEO Optimization",
    "FinTech",
    "EdTech"
  ];
export default tags   